# 1.Regression Recap

###  Recap

**Hypothesis** : H(x) = Wx + b

**Cost Function** : cost(W,b) : the square value of gap between prediction and the real value

**Gradient Descent Algorithm** : Method to figure out the minimum point of Cost Function

# 2.Multivariable Regression

If variable for the result goes more than 1(multivariable), We can simply increase the number of variable on hypothesis

![hypothesis](img/1.png)

But this form is not efficient, as the eqaution goes such long. Thus, we utilize **Matrix** to solve this issue. Utilizing **Matrix Multiplication**, we can solve the problem of lenghty Hypothesis.


![hypothesis2](img/2.png)

Matrix Multiplication let us to write the hypothesis in easy way.

Moreover, if there exists more instanes (number of data) on the data table, we can make the whole data in matrix form. We don't have to calculate single instances for multiple times.

![matrix](img/3.png)

Table above includes 5 instances.

![matrix2](img/4.png)

Thus, the matrix above illustrates important concepts of the matrix implication

n : the number of instances (data sets) <br />
3 : the number of variables for the result <br/>
3 : the number of weights (as same with the variable number)


### Hypothesis with formula way

In [1]:
import tensorflow as tf

#data definition
x1_data = [73., 93., 89., 96., 73.,]
x2_data = [80., 88., 91., 98., 66.,]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

#placeholders for variables, to figure out optimal value
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y= tf.placeholder(tf.float32)

#placeholders for weight
w1 = tf.Variable(tf.random_normal([1]), name='weight1') #variable with random value, but the number exists only one
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

#Hypothesis
hypothesis = x1*w1 + x2*w2 + x3*w3 + b

In [2]:
#Cost Function and Gradient-Descent
cost = tf.reduce_mean(tf.square(hypothesis-Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [3]:
#Launch the Graph
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1:x1_data, x2:x2_data, x3:x3_data, Y:y_data})
    if step % 10 == 0:
        print(step, "Cost ", cost_val, "\n Prediction:", hy_val)

(0, 'Cost ', 2223.0649, '\n Prediction:', array([ 114.57369995,  131.17602539,  132.70941162,  143.64465332,
         99.10366058], dtype=float32))
(10, 'Cost ', 11.990341, '\n Prediction:', array([ 156.15644836,  181.18054199,  181.96662903,  197.28593445,
        137.24961853], dtype=float32))
(20, 'Cost ', 11.906515, '\n Prediction:', array([ 156.26902771,  181.34094238,  182.1116333 ,  197.44523621,
        137.37705994], dtype=float32))
(30, 'Cost ', 11.843262, '\n Prediction:', array([ 156.25614929,  181.35049438,  182.10804749,  197.44271851,
        137.38943481], dtype=float32))
(40, 'Cost ', 11.780319, '\n Prediction:', array([ 156.24291992,  181.35957336,  182.10400391,  197.43968201,
        137.40141296], dtype=float32))
(50, 'Cost ', 11.71777, '\n Prediction:', array([ 156.22975159,  181.36862183,  182.09997559,  197.43670654,
        137.41337585], dtype=float32))
(60, 'Cost ', 11.655492, '\n Prediction:', array([ 156.21658325,  181.37763977,  182.09594727,  197.4336853 

### Matrix Way

In [4]:
#data illustation in matrix

x_data = [[73., 80., 75.], [93., 88., 93.], [89.,91.,90.], [96., 98., 100.], [73., 66., 70.]] #5X3 Matrix
y_data = [[152.],[185.],[180.],[196.],[142.]] #5X1 Matrix

#placeholder for a tensor
#For placeholder, necessary to define number of instances
X = tf.placeholder(tf.float32, shape=[None, 3]) #shape=[Number of instances(None if not fixed), Number of variable]
Y = tf.placeholder(tf.float32, shape=[None, 1])

#For Variable, does not have to define the number of instances, just the form of matrix
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

#Hypothesis
hypothesis = tf.matmul(X,W) + b #matmul means matrix multiplication
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [5]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    
    if step % 10 == 0:
        print(step, cost_val, hy_val)

(0, 274674.06, array([[-323.44488525],
       [-367.82479858],
       [-373.46505737],
       [-402.29196167],
       [-279.22479248]], dtype=float32))
(10, 38.60252, array([[ 140.16877747],
       [ 189.36193848],
       [ 175.56263733],
       [ 195.58192444],
       [ 145.76075745]], dtype=float32))
(20, 35.914013, array([[ 141.59384155],
       [ 191.03257751],
       [ 177.23075867],
       [ 197.39498901],
       [ 147.02745056]], dtype=float32))
(30, 35.740498, array([[ 141.6204071 ],
       [ 191.02243042],
       [ 177.24275208],
       [ 197.40452576],
       [ 147.01216125]], dtype=float32))
(40, 35.568066, array([[ 141.64271545],
       [ 191.00730896],
       [ 177.24972534],
       [ 197.40864563],
       [ 146.99308777]], dtype=float32))
(50, 35.396446, array([[ 141.66491699],
       [ 190.99215698],
       [ 177.25665283],
       [ 197.41270447],
       [ 146.97399902]], dtype=float32))
(60, 35.225765, array([[ 141.68707275],
       [ 190.97705078],
       [ 177.2635498

# 3.  How to read Data on Tensorflow?

Use loadtxt, with numpy libraries.

### Slicing

In [6]:
import numpy as np

nums = range(5)
print nums

print nums[2:4]
print nums[:-1] #exclude the last one

[0, 1, 2, 3, 4]
[2, 3]
[0, 1, 2, 3]


### Numpy Array

In [7]:
a = np.array([1,2,3,4,5])
#array([1,2,3,4,5])

a[1:3]
a[-1]
a[:-1]

array([1, 2, 3, 4])

In [13]:
# : means take all value
# [x,y] : x means column, y means row

b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(b)

x = b[:,0]
print(x)

y = b[0,:]
print(y)

print('a')

z = b[:2] # [:2] takes to the 2 rows from the top
print(z)

q = b[-1:] #[2:] excepts 2 rows from the top
print(q)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 5 9]
[1 2 3 4]
a
[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]]


### Usage of Filename Queue & Batch

If we take a huge amout of data for the training, it would be hard a single memory can afford the whole proess. Thus, Tensorflow provides the concept of Queue, that generating the Queue of data and read it seperately, and decode it for example queue for actual training.

![queue](img/5.png)


1. It takes the array of filenames in string
2. It reads the key, and value
3. It records it with specified form of data (float maybe), and decode it as csv

In [14]:
import tensorflow as tf

#step01: Queue the filename
filename_queue = tf.train.string_input_producer(['test_score.csv'], shuffle=False, name='filename_queue')

#step02: Reader, read the filename queue
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

#step03: define the type of data as float, and decode it
record_defaults = [[0.],[0.],[0.],[0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

#Batch : Batch the data only with the size of 10 (batch size)
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

#placeholder
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

#Hypothesis
hypothesis = tf.matmul(X,W) + b
cost = tf.reduce_mean(tf.square(hypothesis-Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

#Session
sess = tf.Session()
sess.run(tf.global_variables_initializer())

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost,hypothesis,train], feed_dict={X:x_batch, Y:y_batch})

    if step % 10 == 0: 
        print(step, cost_val, hy_val)


(0, 4362.3877, array([[ 103.94567871],
       [ 108.69426727],
       [ 115.71366119],
       [ 122.23381805],
       [  82.12656403],
       [  53.08708954],
       [  90.63741302],
       [  66.40740967],
       [  93.33440399],
       [  76.8177948 ]], dtype=float32))
(10, 123.83647, array([[ 162.66169739],
       [ 179.35331726],
       [ 185.28785706],
       [ 198.0304718 ],
       [ 136.01670837],
       [  92.86708069],
       [ 147.38653564],
       [ 108.49287415],
       [ 159.42132568],
       [ 138.09365845]], dtype=float32))
(20, 119.02877, array([[ 163.01449585],
       [ 179.85351562],
       [ 185.73956299],
       [ 198.54510498],
       [ 136.39842224],
       [  93.19238281],
       [ 147.78411865],
       [ 108.80261993],
       [ 159.93414307],
       [ 138.62561035]], dtype=float32))
(30, 117.91943, array([[ 162.97364807],
       [ 179.88017273],
       [ 185.72496033],
       [ 198.55175781],
       [ 136.41897583],
       [  93.25119019],
       [ 147.80136108]

# 4. Logistic Regression

